/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PartnersImport } from './routes/partners'
import { Route as CompaniesImport } from './routes/companies'
import { Route as IndexImport } from './routes/index'
import { Route as WorkshopsIndexImport } from './routes/workshops/index'
import { Route as WorkshopsWorkshopIdImport } from './routes/workshops/$workshopId'

// Create/Update Routes

const PartnersRoute = PartnersImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesRoute = CompaniesImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkshopsIndexRoute = WorkshopsIndexImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => rootRoute,
} as any)

const WorkshopsWorkshopIdRoute = WorkshopsWorkshopIdImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesImport
      parentRoute: typeof rootRoute
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersImport
      parentRoute: typeof rootRoute
    }
    '/workshops/$workshopId': {
      id: '/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof WorkshopsWorkshopIdImport
      parentRoute: typeof rootRoute
    }
    '/workshops/': {
      id: '/workshops/'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/partners': typeof PartnersRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops': typeof WorkshopsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/partners': typeof PartnersRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops': typeof WorkshopsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/partners': typeof PartnersRoute
  '/workshops/$workshopId': typeof WorkshopsWorkshopIdRoute
  '/workshops/': typeof WorkshopsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/partners'
    | '/workshops/$workshopId'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies' | '/partners' | '/workshops/$workshopId' | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/partners'
    | '/workshops/$workshopId'
    | '/workshops/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  PartnersRoute: typeof PartnersRoute
  WorkshopsWorkshopIdRoute: typeof WorkshopsWorkshopIdRoute
  WorkshopsIndexRoute: typeof WorkshopsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  PartnersRoute: PartnersRoute,
  WorkshopsWorkshopIdRoute: WorkshopsWorkshopIdRoute,
  WorkshopsIndexRoute: WorkshopsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/companies",
        "/partners",
        "/workshops/$workshopId",
        "/workshops/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/companies": {
      "filePath": "companies.tsx"
    },
    "/partners": {
      "filePath": "partners.tsx"
    },
    "/workshops/$workshopId": {
      "filePath": "workshops/$workshopId.tsx"
    },
    "/workshops/": {
      "filePath": "workshops/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
